sudo: required
language: bash
notifications:
  email: true
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
- sleep 2  # Hack to guarantee BUILD_TS is newer than `git checkout` last-modified timestamp.
- export BUILD_ID=$TRAVIS_BUILD_ID
- export BUILD_TS=$(date -u +%s)
script:
- make build
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
  - secure: "PDsz2eTTz44Q//tjpTDKi+A1x+bR4FzTHNwJowlmviV6njQcALlpQrGfbYHccVgitlj6K2Wr5+74OKFvqurKpxlabm2OjdEJzKX63CKPSKn2k9DkuVYLpsZDkGVjD1bqbIowzfbRq891UqO/dHUOOttL5ZANEtvSrkg9NQFHY08NPyJgS/HcuU6nYFjFuTSLFxvhZizID6cKP7fUUclCwMK4skhcd05SnSchdHGOat4lN4NZw0VRYh9mwsYIcgA5yqoroXdm8X3IkudiuVDgmei/antgwi67HbvgLhoqCWbf5ryTQ/00wei2cI6f00ucVBLMJ9JD4+1KRK7UYivXzggYDPE2XB2/bZMVLm3b1q4Y0mGyqttH3F7YL/NgpV5xENXhAIhc9tN13Mj2rC8BLiVVINiCtfC3aZe93vx1th1BDaIbPm5Ds4ApdYBSMSHr7TVHDRv5tupg8ZlRjO3/HviHqBJ0Yd6JSSTx+fUsFbm/Pje5Nx4ATw99AQqm3LLQPW6YgM+3/GUogB2F7ZVuZNaOMjYDNurDEcQGVc+cJX6humb6tNJ56wWBGYsBtpu/QnFhpBL2iBt62/IzyH5n6u90QHjW2CswWblvXyzbq9CNF4iRDNe4FenJeoP1h492ryX/DLJin6we/eISA1UVLBogfWsvz9vTksMLpd23Goo="
  - secure: "n+uEfdrJ2tx9Px6zbtdYwcRQd9on11gY/hg1OcM6DzxjRKXqW+dUfNL489LOXg8Vke6ATfdp2U+EcqnPO48HddIuG7HQqUGW7wQvXj6ypT8w0T7lD5xjrRaUqU+Ni4yWYzqNSGt7rVSiM+rllqxYxsYq3UrNStUBsX7CODNW9m3Le6CUOCOrAfVAcnJbm7FF4MkwJ1EDQjdutHX84zRMIwM+yv7ZjFmm8X80GjQJcFPa6h3zW9SuerAh6VGhjKhgxYnQ8R8boYy+IInNC6xVC9LOMK0l9OaS3e0Q3sTHnYMm2fnOuONmPgI4wztrRu6MeFItHVOJednVQqYeMFbq1fD8J9e9qTrMhoCSuh6gyLJeAEpbKEArA9ovCZv4aYb0Bf5zbfkESd+m39uuMEDrh0z1uaokLN9GH3xh/GRnkMEO7gvyS2IVMcxHLw8jvxBzlB0nXCqEkYQ/XZbmfsw5WEXt0N5rfajY2SvkaY6pKhbfjZQ6saoYRI9HsIhs0m3akX+qQ618OTnQ0rWMeOi65ibj9XBLjLx/G2Xz/4M6sDG/dVf8FF/BUWUFdZPlYt7/KZ90K4T8xPzuYzpCYlhizc/SedQnV9h6TWoJvAgGKbgcMqQ4LeBEKL/Ina8NH9qEbmCJowPbd+NerZi16zPD6Y0kCkpb8uyigOX3/mStsXc="
