# Version.make
#
# Generic Makefile symlinked into image version directories for building from local Dockerfiles.
.DEFAULT_GOAL := help

RELATIVE_COMMON_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RELATIVE_COMMON_ENVFILE ?= $(RELATIVE_COMMON_DIR)/.env
ifneq ($(strip $(wildcard $(RELATIVE_COMMON_ENVFILE))),)
	include $(RELATIVE_COMMON_ENVFILE)
	export $(shell sed 's/=.*//' $(RELATIVE_COMMON_ENVFILE))
endif

ENVFILE ?= .env
ifneq ($(strip $(wildcard $(ENVFILE))),)
	include $(ENVFILE)
	export $(shell sed 's/=.*//' $(ENVFILE))
endif

ifndef DOCKERFILES_DIR
$(error Required variable 'DOCKERFILES_DIR' not set)
endif

LOGGERFILE ?= $(DOCKERFILES_DIR)/.logger
ifneq ($(strip $(wildcard $(LOGGERFILE))),)
	include $(LOGGERFILE)
endif

BUILD_DEPS := $(shell find . -type f \( -iname '*' ! -iname '*build' \))
BASE_IMAGE_DEPS := $(shell grep -ril "^IMAGE=$(BASE_IMAGE)" $(DOCKERFILES_DIR) | xargs dirname)

$(BASE_IMAGE)-%:
	$(call TRACE, [$(IMAGE)] - Running '$*' for base image '$(BASE_IMAGE)')
	@$(MAKE) -C $(BASE_IMAGE_DEPS) $*
	@if [ "$*" != "clean" ]; then \
		echo $(REPO)/$(BASE_IMAGE):$(TAG) > $@ && touch -t $(BUILD_TS_TOUCH) $@; \
	fi;
	$(call TRACE, [$(IMAGE)] - Completed '$*' for base image '$(BASE_IMAGE)')

all: build deploy | all-requirements  ## Build and deploy image created from Dockerfile.

build: $(BASE_IMAGE)-build $(BUILD_DEPS) | build-requirements  ## Build image from Dockerfile.
	$(call TRACE, [$(IMAGE)] - Running '$@')
	@docker build \
		--rm \
		--force-rm \
		--cache-from $(IMAGE):latest \
		$(foreach tag,$(TAGS),--tag $(tag)) \
		$(foreach label,$(LABELS),--label $(label)) \
		$(foreach arg,$(ARGS),--build-arg $(arg)) \
		--file $(shell pwd)/Dockerfile \
		.
	@echo $(REPO)/$(IMAGE):$(TAG) > $@ && touch -t $(BUILD_TS_TOUCH) $@
	$(call TRACE, [$(IMAGE)] - Completed '$@')

.PHONY: clean
clean: $(BASE_IMAGE)-clean | clean-requirements  ## Clean state generated by previous images built from Dockerfile.
	$(call TRACE, [$(IMAGE)] - Running '$@')
	@rm *build > /dev/null 2>&1 || true
	@docker system prune --all --force --filter "label=$(LABEL_PREFIX).image=$(IMAGE)" --filter "until=$(BUILD_TS)"
	$(call TRACE, [$(IMAGE)] - Completed '$@')

deploy: build $(BASE_IMAGE)-deploy | deploy-requirements  ## Deploy image built from Dockerfile.
	$(call TRACE, [$(IMAGE)] - Running '$@')
	@for tag in $(TAGS) ; do docker push $$tag ; done
	@echo $(REPO)/$(IMAGE):$(TAG) > $@ && touch -t $(BUILD_TS_TOUCH) $@
	$(call TRACE, [$(IMAGE)] - Completed '$@')

.PHONY: all-requirements
all-requirements: build-requirements deploy-requirements

.PHONY: build-requirements
build-requirements: requires-REPO \
	requires-LABEL_PREFIX \
	requires-TAG \
	requires-IMAGE \
	requires-BASE_IMAGE \
	requires-TAGS \
	requires-LABELS \
	requires-ARGS

.PHONY: clean-requirements
clean-requirements: requires-IMAGE \
	requires-LABEL_PREFIX \
	requires-BUILD_TS

.PHONY: deploy-requirements
deploy-requirements: requires-REPO \
	requires-TAG \
	requires-IMAGE \
	requires-TAGS

requires-%:
	@if [ -z '${${*}}' ]; then echo 'Required variable "$*" not set' && exit 1; fi

.PHONY: help
help: ## Print Makefile usage.
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
